name: CI

on:
 push:
  branches: [master, develop]
 pull_request:
  branches: [master, develop]

jobs:
 build-and-test:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    directory: [client, server]

  steps:
   - uses: actions/checkout@v3

   - name: Use Node.js
     uses: actions/setup-node@v3
     with:
      node-version: "18"

   - name: Install all dependencies (monorepo)
     run: npm install

   - name: Build (only client)
     if: matrix.directory == 'client'
     run: npm run build
     working-directory: client

 integration-tests:
  runs-on: ubuntu-latest
  needs: build-and-test

  steps:
   - uses: actions/checkout@v3

   - name: Use Node.js
     uses: actions/setup-node@v3
     with:
      node-version: "18"

   - name: Install all dependencies (monorepo)
     run: npm install

   - name: Run integration tests
     run: npm run test:integration
     working-directory: server

 unit-tests:
  runs-on: ubuntu-latest
  needs: build-and-test

  steps:
   - uses: actions/checkout@v3

   - name: Use Node.js
     uses: actions/setup-node@v3
     with:
      node-version: "18"

   - name: Install all dependencies (monorepo)
     run: npm install

   - name: Run unit tests
     run: npm run test:unit
     working-directory: server
