name: CI

on:
 push:
  branches: [master, develop]
 pull_request:
  branches: [master, develop]

jobs:
 build-and-test:
  runs-on: ubuntu-latest

  strategy:
   matrix:
    directory: [client, server]

  steps:
   - uses: actions/checkout@v3

   - name: Use Node.js
     uses: actions/setup-node@v3
     with:
      node-version: "18"

   - name: Install dependencies
     run: npm install
     working-directory: ${{ matrix.directory }}

   - name: Run tests
     run: npm test
     working-directory: ${{ matrix.directory }}

   - name: Build (only client)
     if: matrix.directory == 'client'
     run: npm run build
     working-directory: client
